# Generated by Django 4.2.3 on 2023-07-10 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('dimension', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('lastModifiedBy', models.ForeignKey(limit_choices_to={'groups__name': 'MapScanners'}, on_delete=django.db.models.deletion.CASCADE, related_name='scanned_blocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='minecraftblock',
            constraint=models.UniqueConstraint(fields=('x', 'y', 'z', 'dimension'), name='unique_block'),
        ),
    ]
